# Generated by Django 4.1.4 on 2023-01-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('elevation', models.IntegerField()),
                ('description', models.TextField(max_length=300)),
            ],
        ),
    ]
